### ISSUE TITLE
Is not discovering any of my PowerView shades

### ISSUE THREAD

**Issue by tkhan456** [safepay/cover.hd_powerview#2]
Not sure why, but installed through HACS and will not discover any of the shades (all bottom-up, PowerView)

**Comment by tkhan456** [comment]
This is the only error I'm seeing:

hd_powerview: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/config/custom_components/hd_powerview/cover.py", line 109, in async_update
    self._cover_data = self._pv.get_shade(self._cover_id)
  File "/config/custom_components/hd_powerview/cover.py", line 155, in get_shade
    shade = Shade(request['shade']['id'], b64decode(request['shade']['name']).decode('UTF-8'), round((request['shade']['positions']['position1'] / 65535) * 100), round(request['batteryStrength'] / 2))
KeyError: 'batteryStrength

**Comment by safepay** [comment]
Yes. There is a bug in the keys for the battery_level. This is updated in the master but not in the latest release.
